In [3]:
import torch
import numpy as np

In [6]:
a = [1,2,3]
b = [i+2 for i in a]
print(a)
print(b)

[1, 2, 3]
[3, 4, 5]


In [7]:
a1 = np.asarray(a)
b1 = a1+2
print(a1)
print(b1)

[1 2 3]
[3 4 5]


In [9]:
a2 = torch.Tensor(a)
b2 = a2+2
print(a2)
print(b2)

tensor([1., 2., 3.])
tensor([3., 4., 5.])


In [12]:
a3 = torch.Tensor(a)
b3 = torch.Tensor(a3)
b3.add_(2)
print(a3)
print(b3)

tensor([3., 4., 5.])
tensor([3., 4., 5.])
